spring:
  # servlet:
  #   max-request-size: 300MB
  #   max-file-size: 30MB
  # document:
  #   uploadPath: /data/images/
  #   imPath: http://8080/springboot/images/
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    auto-commit: false
    connection-timeout: 3000
    validation-timeout: 3000
    max-lifetime: 300000
    maximum-pool-size: 20
    minimum-idle: 1

mybatis:
  mapper-locations: classpath:mappers/*.xml